facebook:
  label: Facebook
  permalink: /facebook
  description: Facebook tag description

hello:
  label: Hello
  permalink: /hello
  description: Hello tag description

docusaurus:
  label: Docusaurus
  permalink: /docusaurus
  description: Docusaurus tag description

hola:
  label: Hola
  permalink: /hola
  description: Hola tag description

wordpress:
  label: WordPress
  permalink: /wordpress
  description: WordPress and related ecosystem

kinsta:
  label: Kinsta
  permalink: /kinsta
  description: Kinsta hosting and reliability

reliability:
  label: Reliability
  permalink: /reliability
  description: Reliability, SRE, and operations

review:
  label: Review
  permalink: /review
  description: Reviews and evaluations

devlog:
  label: Devlog
  permalink: /devlog
  description: Devlog tag

agent:
  label: Agent
  permalink: /agent
  description: Agent tag

ai:
  label: Ai
  permalink: /ai
  description: Ai tag

llm:
  label: LLM
  permalink: /llm
  description: LLM and model releases

drupal:
  label: Drupal
  permalink: /drupal
  description: Drupal CMS and ecosystem

cms:
  label: CMS
  permalink: /cms
  description: Content management systems

content:
  label: Content
  permalink: /content
  description: Content and workflows

workflow:
  label: Workflow
  permalink: /workflow
  description: Workflows and processes

drupal-commerce:
  label: Drupal Commerce
  permalink: /drupal-commerce
  description: Drupal Commerce and B2B

b2b:
  label: B2B
  permalink: /b2b
  description: B2B and commerce

ddev:
  label: DDEV
  permalink: /ddev
  description: DDEV local development

devops:
  label: DevOps
  permalink: /devops
  description: DevOps and infrastructure

drupal-cms:
  label: Drupal CMS
  permalink: /drupal-cms
  description: Drupal CMS and Starshot

starshot:
  label: Starshot
  permalink: /starshot
  description: Drupal Starshot initiative

recipes:
  label: Recipes
  permalink: /recipes
  description: Drupal recipes and site building

agentic:
  label: Agentic
  permalink: /agentic
  description: Agentic AI and automation

enterprise:
  label: Enterprise
  permalink: /enterprise
  description: Enterprise and scale

playbook:
  label: Playbook
  permalink: /playbook
  description: Playbooks and guides

build:
  label: Build
  permalink: /build
  description: Build and deliverables

php:
  label: Php
  permalink: /php
  description: Php tag

symfony:
  label: Symfony
  permalink: /symfony
  description: Symfony tag

backend:
  label: Backend
  permalink: /backend
  description: Backend tag

playwright:
  label: Playwright
  permalink: /playwright
  description: Playwright tag

python:
  label: Python
  permalink: /python
  description: Python tag

performance:
  label: Performance
  permalink: /performance
  description: Performance tag

jsonapi:
  label: Jsonapi
  permalink: /jsonapi
  description: Jsonapi tag

opus:
  label: Opus
  permalink: /opus
  description: Opus tag

codex:
  label: Codex
  permalink: /codex
  description: Codex tag

government:
  label: Government
  permalink: /government
  description: Government tag

open-source:
  label: Open Source
  permalink: /open-source
  description: Open Source tag

digital-sovereignty:
  label: Digital Sovereignty
  permalink: /digital-sovereignty
  description: Digital Sovereignty tag

analysis:
  label: Analysis
  permalink: /analysis
  description: Analysis tag

quality:
  label: Quality
  permalink: /quality
  description: Quality tag

cloudflare:
  label: Cloudflare
  permalink: /cloudflare
  description: Cloudflare tag

cli:
  label: Cli
  permalink: /cli
  description: Cli tag

ops:
  label: Ops
  permalink: /ops
  description: Ops tag

pantheon:
  label: Pantheon
  permalink: /pantheon
  description: Pantheon tag

automation:
  label: Automation
  permalink: /automation
  description: Automation tag
